### ISSUE TITLE
Add YAML configuration validator 

### ISSUE THREAD

**Issue by kavs2803** [acmpesuecc/ModelForge#2]
The system currently lacks a way to validate the YAML configuration file before processing begins. This can lead to errors if required fields are missing or incorrectly set, causing unexpected behavior during runtime.

We need to implement a YAML configuration validator that checks for necessary fields and ensures the correct data types are used across the entire configuration. This validation should run before any processing or model training starts to prevent errors later in the pipeline.

Below is one of the yaml files used for ModelForge for your reference :

```yaml
dataset:
  path: "datasets/news-classify.csv" 
  format: csv 
  delimiter: "," 

input_features:
  - name: Text 
    type: text 
    encoder: parallel_cnn
    params:
      embedding_size: 256
      num_filters: 256
      filter_sizes: [3, 4, 5]
      num_fc_layers: 2
      vocab_size: 10000
      fc_size: 256
      dropout: 0.5
      output_size: 512
      
output_features:
  - name: category
    type: Category 
    num_classes: 5
    
training:
  - learning_rate: 0.001
    batch_size: 32
    num_epochs: 15

preprocessing:
  split:
    train: 0.7
    test: 0.2
    validation: 0.1
    random_seed: 42 
  text:
    lower_case: true 
    remove_punctuation: true 
    remove_stopwords: true 
    stemming: false 
    tokenization: 
      method: word 
```

Required Fields for Preprocessing Validation:
**dataset**
**input_features**
**output_features**
**training**
**preprocessing**
